// <auto-generated />
using EcoSync.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoSync.Migrations
{
    [DbContext(typeof(DbContextClass))]
    partial class DbContextClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoSync.Models.Bairro", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<double>("AreaEmKm2")
                        .HasColumnType("double precision");

                    b.Property<int>("DensidadePopulacional")
                        .HasColumnType("integer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Pontuacoesid")
                        .HasColumnType("integer");

                    b.HasKey("Nome");

                    b.HasIndex("Pontuacoesid");

                    b.ToTable("Bairros");
                });

            modelBuilder.Entity("EcoSync.Models.Pontuacoes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("AreaVerde")
                        .HasColumnType("double precision");

                    b.Property<double>("DensidadePopulacional")
                        .HasColumnType("double precision");

                    b.Property<double>("Educacao")
                        .HasColumnType("double precision");

                    b.Property<double>("PoluicaoSonoraEArTransito")
                        .HasColumnType("double precision");

                    b.Property<double>("Saude")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("Pontuacoes");
                });

            modelBuilder.Entity("EcoSync.Models.Bairro", b =>
                {
                    b.HasOne("EcoSync.Models.Pontuacoes", "Pontuacoes")
                        .WithMany()
                        .HasForeignKey("Pontuacoesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pontuacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
