version: '3.8'
services:
  ecosyncdb:
    image: postgres
    container_name: ecosyncdb
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Root@123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ecosync-network

  ecosync:
    image: ecosync
    build:
      context: .
      dockerfile: EcoSync/Dockerfile
    depends_on:
      ecosyncdb:
        condition: service_healthy
    networks:
      - ecosync-network
    ports:
      - "8080:8080"
      - "8081:8081"

networks:
  ecosync-network:
    driver: bridge