# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  ecosync:
    build:
      context: "/Users/atilaalcantara/Documents/ProjetosPessoais/EcoSync"
      dockerfile: "EcoSync/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ecosync:dev"
    ports:
    - "127.0.0.1:57007:57000"
    - "127.0.0.1:57207:57200"
    - "127.0.0.1:57407:57400"
    volumes:
    - "/Users/atilaalcantara/Documents/ProjetosPessoais/EcoSync/EcoSync:/app:rw"
    - "/Users/atilaalcantara/Documents/ProjetosPessoais/EcoSync:/src:rw"
    - "/Users/atilaalcantara/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/atilaalcantara/.local/share/JetBrains/RiderRemoteDebugger/2024.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/atilaalcantara/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/atilaalcantara/Library/Logs/JetBrains/Rider2024.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_11_30_15_16_50:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
